### ISSUE TITLE
support for simple csv

### ISSUE THREAD

**Issue by astrakid** [mnadeem/wishing-app#1]
hi,
would it be possible to use simple csvs? that would help us to automatically create and maintain birthday-lists.

regards,
andre

**Comment by mnadeem** [comment]
Thats a good idea, meanwhile, you can convert a csv to xlsx and use it.

**Comment by mnadeem** [comment]
Next release would have support for CSV, Coding has been done (https://github.com/mnadeem/wishing-app/blob/master/src/main/java/com/github/mnadeem/wishing/service/support/CsvWishFileReader.java)

**Comment by mnadeem** [comment]
v2.1 released, refer https://github.com/mnadeem/wishing-app/wiki/Workbook-Loading-Options this for more details on how use csv files.

**Comment by astrakid** [comment]
very cool, thx a lot. will test it after my holidays. but i assume it will work. thanks a lot once again.

**Comment by mnadeem** [comment]
give a like to project if it is helpful
